title: Abhayjeet Singh
position: Research Associate
affiliation: Indian Institute of Sciences(IISc), Bangalore, India
email: singh.abhayjeet242@gmail.com
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=8yz86tUAAAAJ&hl=en
github_link: https://github.com/Abhay242
linkedin: https://www.linkedin.com/in/abhayjeet-singh-9a9a27122/
avatar: ./assets/img/avatar.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
