title: Abhayjeet Singh
position: Research Associate
affiliation: Indian Institute of Sciences(IISc), Bangalore, India
email: singh.abhayjeet242@gmail.com
keywords: Abhayjeet Singh IISc AI Speech
google_scholar: https://scholar.google.com/citations?user=8yz86tUAAAAJ&hl=en
github_link: https://github.com/Abhay242
linkedin: https://www.linkedin.com/in/abhayjeet-singh-9a9a27122/
avatar: ./assets/img/avatar.jpg
google_analytics: G-FXR1409DSH
favicon: ./assets/img/favicon.jpg
favicon_dark: ./assets/img/favicon_dark.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
